"""
RailVinyas AI - FastAPI Backend

Project structure:

Block_debugger/
├── backend/
│   ├── __init__.py
│   ├── app.py
│   ├── auth.py
│   └── railvinyas.db
│
├── data/
│   ├── real/
│   ├── derived/
│   └── synthetic/
│
├── training/
├── models/
├── raw/
├── notebooks/
├── railvinyas-frontend/
│   ├── src/
│   ├── package.json
│   └── dist/                  # generated by npm run build
│
└── requirements.txt

Local development:
    uvicorn backend.app:app --reload --port 8000

Render:
    python -m uvicorn backend.app:app --host 0.0.0.0 --port $PORT
"""

from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from fastapi import Depends, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from backend.auth import (
    get_current_user,
    init_db,
    router as auth_router,
)


# ============================================================
# APPLICATION
# ============================================================

app = FastAPI(
    title="RailVinyas AI API",
    description=(
        "AI-powered railway maintenance block planning and "
        "optimization system."
    ),
    version="1.0.0",
)


# ============================================================
# DATABASE / AUTHENTICATION
# ============================================================

# Initialize SQLite database and required tables.
init_db()

# Authentication routes:
# /api/auth/register
# /api/auth/login
# /api/auth/verify-otp
# /api/auth/me
app.include_router(auth_router)


# ============================================================
# CORS
# ============================================================

# Broad CORS is acceptable for the initial prototype deployment.
# Once the final public frontend URL is known, this can be
# restricted to that domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# PROJECT PATHS
# ============================================================

# app.py is inside:
# Block_debugger/backend/app.py
#
# Therefore:
# parent       -> backend
# parent.parent -> Block_debugger
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_REAL = BASE_DIR / "data" / "real"
DATA_DERIVED = BASE_DIR / "data" / "derived"
DATA_SYNTHETIC = BASE_DIR / "data" / "synthetic"

TRAINING_DIR = BASE_DIR / "training"
MODELS_DIR = BASE_DIR / "models"

FRONTEND_DIST = BASE_DIR / "railvinyas-frontend" / "dist"


# ============================================================
# LOAD DATA AND MODEL ON STARTUP
# ============================================================

traffic = pd.read_csv(
    DATA_DERIVED / "03_section_traffic_derived.csv"
)

assets = pd.read_csv(
    DATA_SYNTHETIC / "04_asset_register.csv"
)

avail = pd.read_csv(
    DATA_SYNTHETIC / "06_daily_asset_availability.csv",
    parse_dates=["date"],
)

train_table = pd.read_csv(
    TRAINING_DIR / "07_model_training_table.csv",
    parse_dates=["date"],
)

model = joblib.load(
    MODELS_DIR / "overrun_model.joblib"
)

feature_columns = joblib.load(
    MODELS_DIR / "model_feature_columns.joblib"
)


# ============================================================
# PRECOMPUTED LOOKUPS
# ============================================================

traffic_idx = traffic.set_index(
    ["section_id", "hour_of_day"]
)[
    ["trains_count", "traffic_level"]
]


assets_count_idx = (
    assets
    .groupby(["home_section_id", "asset_type"])
    .size()
)


latest_section_rate = (
    train_table
    .sort_values("date")
    .groupby("section_id")[
        "section_historical_overrun_rate"
    ]
    .last()
)


global_fallback_rate = (
    float(train_table["overrun_flag"].mean())
    if not train_table.empty
    else 0.0
)


avail_with_type = avail.merge(
    assets[["asset_id", "asset_type"]],
    on="asset_id",
    how="left",
)


overall_type_avail = (
    avail_with_type
    .groupby("asset_type")["available"]
    .apply(lambda s: (s == "YES").mean())
)


# Features that require one-hot encoding.
CATEGORICAL = [
    "day_of_week",
    "maintenance_type",
    "required_asset_type",
    "priority",
    "weather",
    "traffic_level",
]


# ============================================================
# REQUEST MODEL
# ============================================================

class BlockRequest(BaseModel):
    section_id: str
    maintenance_type: str
    required_asset_type: str
    priority: str
    weather: str
    planned_duration_min: float
    date: str  # YYYY-MM-DD


# ============================================================
# HOURLY SCORING
# ============================================================

def score_hour(
    section_id: str,
    hour: int,
    maintenance_type: str,
    required_asset_type: str,
    priority: str,
    weather: str,
    planned_duration_min: float,
    date: str,
):
    """
    Calculate the expected operational impact of a maintenance
    block starting at a particular hour.
    """

    # --------------------------------------------------------
    # 1. Traffic
    # --------------------------------------------------------

    try:
        trains_count, traffic_level = traffic_idx.loc[
            (section_id, hour)
        ]

    except KeyError:
        trains_count = 0.0
        traffic_level = "LOW"


    # --------------------------------------------------------
    # 2. Assets available in the requested section
    # --------------------------------------------------------

    assets_here = assets_count_idx.get(
        (section_id, required_asset_type),
        0,
    )


    # --------------------------------------------------------
    # 3. Daily asset availability
    # --------------------------------------------------------

    target_date = pd.Timestamp(date)

    day_records = avail_with_type[
        (avail_with_type["date"] == target_date)
        &
        (
            avail_with_type["asset_type"]
            == required_asset_type
        )
    ]


    if len(day_records) > 0:

        avail_pct = (
            day_records["available"] == "YES"
        ).mean()

        had_record = 1

    else:

        avail_pct = overall_type_avail.get(
            required_asset_type,
            0.7,
        )

        had_record = 0


    # --------------------------------------------------------
    # 4. Historical section overrun rate
    # --------------------------------------------------------

    section_rate = latest_section_rate.get(
        section_id,
        global_fallback_rate,
    )


    # --------------------------------------------------------
    # 5. Date features
    # --------------------------------------------------------

    d = target_date

    day_name = d.day_name()

    is_weekend = int(
        day_name in ["Saturday", "Sunday"]
    )


    # --------------------------------------------------------
    # 6. Create model input
    # --------------------------------------------------------

    raw = pd.DataFrame(
        [
            {
                "day_of_week": day_name,
                "maintenance_type": maintenance_type,
                "required_asset_type": required_asset_type,
                "priority": priority,
                "weather": weather,
                "traffic_level": traffic_level,
                "month": d.month,
                "is_weekend": is_weekend,
                "start_hour": hour,
                "trains_count": trains_count,
                "assets_of_type_in_section": assets_here,
                "asset_type_availability_pct": avail_pct,
                "had_availability_record": had_record,
                "section_historical_overrun_rate": section_rate,
                "planned_duration_min": planned_duration_min,
            }
        ]
    )


    # --------------------------------------------------------
    # 7. One-hot encode categorical variables
    # --------------------------------------------------------

    X_row = (
        pd.get_dummies(
            raw,
            columns=CATEGORICAL,
        )
        .reindex(
            columns=feature_columns,
            fill_value=0,
        )
    )


    # --------------------------------------------------------
    # 8. ML prediction
    # --------------------------------------------------------

    predicted_overrun = float(
        model.predict(X_row)[0]
    )


    # Negative overrun is not operationally useful.
    predicted_overrun = max(
        predicted_overrun,
        0.0,
    )


    # --------------------------------------------------------
    # 9. Expected duration
    # --------------------------------------------------------

    expected_total_duration = (
        planned_duration_min
        + predicted_overrun
    )


    # --------------------------------------------------------
    # 10. Disruption score
    # --------------------------------------------------------

    trains_count = float(trains_count)

    disruption_score = (
        trains_count
        * expected_total_duration
    )


    return {
        "trains_count": trains_count,

        "traffic_level": str(
            traffic_level
        ),

        "predicted_overrun_min": round(
            predicted_overrun,
            1,
        ),

        "expected_total_duration_min": round(
            expected_total_duration,
            1,
        ),

        "asset_type_availability_pct": round(
            float(avail_pct),
            2,
        ),

        "disruption_score": round(
            float(disruption_score),
            1,
        ),
    }


# ============================================================
# HEALTH CHECK
# ============================================================

@app.get("/api/health")
def health():
    """
    Backend health check.

    Example:
        GET /api/health
    """

    return {
        "status": "RailVinyas API is running"
    }


# ============================================================
# SECTION API
# ============================================================

@app.get("/api/sections")
def list_sections(
    user=Depends(get_current_user)
):
    """
    Return available railway section IDs.

    Requires authentication.
    """

    return sorted(
        traffic["section_id"]
        .dropna()
        .unique()
        .tolist()
    )[:1000]


# ============================================================
# RECOMMENDATION API
# ============================================================

@app.post("/api/recommend")
def recommend(
    req: BlockRequest,
    user=Depends(get_current_user),
):
    """
    Generate an AI-assisted maintenance block recommendation.

    The system:

    1. Validates the railway section.
    2. Evaluates all 24 hours.
    3. Predicts maintenance overrun.
    4. Calculates expected duration.
    5. Calculates disruption score.
    6. Ranks candidate hours.
    7. Selects the best maintenance asset.
    """

    # --------------------------------------------------------
    # Validate section
    # --------------------------------------------------------

    if req.section_id not in traffic["section_id"].values:

        raise HTTPException(
            status_code=404,
            detail=(
                f"Unknown section_id "
                f"'{req.section_id}'"
            ),
        )


    # --------------------------------------------------------
    # Evaluate all 24 candidate hours
    # --------------------------------------------------------

    candidates = []

    for hour in range(24):

        result = score_hour(
            section_id=req.section_id,
            hour=hour,
            maintenance_type=req.maintenance_type,
            required_asset_type=req.required_asset_type,
            priority=req.priority,
            weather=req.weather,
            planned_duration_min=req.planned_duration_min,
            date=req.date,
        )

        result["start_hour"] = hour

        candidates.append(result)


    # --------------------------------------------------------
    # Rank candidates
    # --------------------------------------------------------

    ranked = sorted(
        candidates,
        key=lambda x: x["disruption_score"],
    )


    best = ranked[0]


    # --------------------------------------------------------
    # Select maintenance asset
    # --------------------------------------------------------

    asset_candidates = assets[
        assets["asset_type"]
        == req.required_asset_type
    ].copy()


    if len(asset_candidates) > 0:

        # Prefer assets whose home section matches
        # the requested railway section.
        asset_candidates["home_match"] = (
            asset_candidates["home_section_id"]
            == req.section_id
        ).astype(int)


        asset_candidates = (
            asset_candidates
            .sort_values(
                ["home_match", "status"],
                ascending=[False, True],
            )
        )


        raw_selected = (
            asset_candidates.iloc[0]
            .to_dict()
        )


        selected = {
            key: (
                value.item()
                if hasattr(value, "item")
                else value
            )

            for key, value
            in raw_selected.items()
        }

    else:

        selected = None


    # --------------------------------------------------------
    # Final response
    # --------------------------------------------------------

    return {
        "section_id": req.section_id,

        "maintenance_type":
            req.maintenance_type,

        "date":
            req.date,

        "recommended_start_hour":
            best["start_hour"],

        "expected_total_duration_min":
            best["expected_total_duration_min"],

        "predicted_overrun_min":
            best["predicted_overrun_min"],

        "traffic_level":
            best["traffic_level"],

        "trains_count":
            best["trains_count"],

        "disruption_score":
            best["disruption_score"],

        "selected_asset":
            selected,

        "top_5_candidates":
            ranked[:5],
    }


# ============================================================
# REACT FRONTEND
# ============================================================

if FRONTEND_DIST.exists():

    # Serve Vite-generated static assets:
    #
    # /assets/index-xxxx.js
    # /assets/index-xxxx.css
    #
    if (FRONTEND_DIST / "assets").exists():

        app.mount(
            "/assets",
            StaticFiles(
                directory=FRONTEND_DIST / "assets"
            ),
            name="assets",
        )


    @app.get(
        "/",
        include_in_schema=False,
    )
    async def serve_home():

        index_file = (
            FRONTEND_DIST
            / "index.html"
        )

        if index_file.exists():

            return FileResponse(
                index_file
            )

        return JSONResponse(
            {
                "status":
                    "RailVinyas API is running",
                "message":
                    "Frontend build not found.",
            }
        )


    @app.get(
        "/{full_path:path}",
        include_in_schema=False,
    )
    async def serve_frontend(
        full_path: str
    ):

        # Prevent path traversal.
        requested_file = (
            FRONTEND_DIST
            / full_path
        ).resolve()

        frontend_root = (
            FRONTEND_DIST.resolve()
        )

        try:

            requested_file.relative_to(
                frontend_root
            )

        except ValueError:

            return FileResponse(
                FRONTEND_DIST / "index.html"
            )


        # Serve an existing file.
        if requested_file.is_file():

            return FileResponse(
                requested_file
            )


        # React Router fallback.
        return FileResponse(
            FRONTEND_DIST / "index.html"
        )


# ============================================================
# LOCAL DEVELOPMENT
# ============================================================

if __name__ == "__main__":

    import uvicorn

    uvicorn.run(
        "backend.app:app",
        host="127.0.0.1",
        port=8000,
        reload=True,
    )