"""
RailVinyas AI - FastAPI Backend

Project structure:

Block_debugger/
├── backend/
│   ├── __init__.py
│   ├── app.py
│   ├── auth.py
│   └── railvinyas.db
│
├── data/
│   ├── real/
│   ├── derived/
│   └── synthetic/
│
├── training/
├── models/
├── raw/
├── notebooks/
├── railvinyas-frontend/
│   ├── src/
│   ├── package.json
│   └── dist/                  # generated by npm run build
│
└── requirements.txt

Local development (run from the Block_debugger/ root, NOT from inside backend/):
    uvicorn backend.app:app --reload --port 8000

Render:
    python -m uvicorn backend.app:app --host 0.0.0.0 --port $PORT
"""

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import xgboost as xgb

from fastapi import Depends, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from backend.auth import (
    get_current_user,
    get_db,
    init_db,
    require_role,
    router as auth_router,
)
from backend.live import router as live_router, init_live_module


# ============================================================
# APPLICATION
# ============================================================

app = FastAPI(
    title="RailVinyas AI API",
    description=(
        "AI-powered railway maintenance block planning and "
        "optimization system."
    ),
    version="1.0.0",
)


# ============================================================
# DATABASE / AUTHENTICATION
# ============================================================

# Initialize SQLite database and required tables.
init_db()

# Authentication routes:
# /api/auth/register
# /api/auth/login
# /api/auth/verify-otp
# /api/auth/me
app.include_router(auth_router)

# Live tracking routes:
# /api/live/section/{section_id}/projection  (schedule-projected, always on)
# /api/live/train/{train_number}             (optional RailRadar GPS lookup)
app.include_router(live_router)


# ============================================================
# CORS
# ============================================================

# Broad CORS is acceptable for the initial prototype deployment.
# Once the final public frontend URL is known, this can be
# restricted to that domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# PROJECT PATHS
# ============================================================

# app.py is inside:
# Block_debugger/backend/app.py
#
# Therefore:
# parent       -> backend
# parent.parent -> Block_debugger
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_REAL = BASE_DIR / "data" / "real"
DATA_DERIVED = BASE_DIR / "data" / "derived"
DATA_SYNTHETIC = BASE_DIR / "data" / "synthetic"

TRAINING_DIR = BASE_DIR / "training"
MODELS_DIR = BASE_DIR / "models"

FRONTEND_DIST = BASE_DIR / "railvinyas-frontend" / "dist"


# ============================================================
# LOAD DATA AND MODEL ON STARTUP
# ============================================================

traffic = pd.read_csv(
    DATA_DERIVED / "03_section_traffic_derived.csv"
)

assets = pd.read_csv(
    DATA_SYNTHETIC / "04_asset_register.csv"
)

avail = pd.read_csv(
    DATA_SYNTHETIC / "06_daily_asset_availability.csv",
    parse_dates=["date"],
)

train_table = pd.read_csv(
    TRAINING_DIR / "07_model_training_table.csv",
    parse_dates=["date"],
)

# IMPORTANT: loaded via XGBoost's native format (save_model/load_model),
# NOT joblib/pickle. XGBoost's own docs explicitly warn that pickle output
# is unstable across Python and XGBoost versions -- this was the cause of
# the "If you are loading a serialized model..." warning (and occasional
# failures after a Render cold-start, where a fresh container could resolve
# a slightly different xgboost version than the one that pickled the model).
# Native format is version-stable and immune to this problem.
model = xgb.XGBRegressor()
model.load_model(
    MODELS_DIR / "overrun_model.json"
)

feature_columns = joblib.load(
    MODELS_DIR / "model_feature_columns.joblib"
)

# Additional real/derived data used by the dashboard, reports, and
# section-traffic pages below (does not affect the recommend endpoint).
blocks_full = pd.read_csv(
    DATA_SYNTHETIC / "05_maintenance_blocks.csv",
    parse_dates=["date"],
)

stations_master = pd.read_csv(
    DATA_REAL / "01_stations_master.csv"
)

station_name_lookup = (
    stations_master.set_index("station_code")["station_name"].to_dict()
)

try:
    eval_results = pd.read_csv(TRAINING_DIR / "08_evaluation_results.csv")
    AVG_DISRUPTION_REDUCTION = round(
        100 * (1 - eval_results["optimizer_score"].sum() / eval_results["as_scheduled_score"].sum()), 1
    )
except FileNotFoundError:
    eval_results = None
    AVG_DISRUPTION_REDUCTION = None


def section_to_stations(section_id: str):
    """'AAA-BBB' -> ('AAA', 'BBB', 'Station A Name', 'Station B Name')"""
    parts = section_id.split("-")
    if len(parts) != 2:
        return parts[0], parts[-1], parts[0], parts[-1]
    a, b = parts
    return a, b, station_name_lookup.get(a, a), station_name_lookup.get(b, b)


# ============================================================
# PRECOMPUTED LOOKUPS
# ============================================================

traffic_idx = traffic.set_index(
    ["section_id", "hour_of_day"]
)[
    ["trains_count", "traffic_level"]
]

# ------------------------------------------------------------------
# Live Section Panel: loads the real per-train timetable once and
# precomputes per-section hop timings, so live projection is a cheap
# lookup per request rather than scanning 186k rows every time.
# ------------------------------------------------------------------
train_timetable = pd.read_csv(DATA_REAL / "02_train_timetable.csv")
init_live_module(train_timetable, traffic_idx)


assets_count_idx = (
    assets
    .groupby(["home_section_id", "asset_type"])
    .size()
)


latest_section_rate = (
    train_table
    .sort_values("date")
    .groupby("section_id")[
        "section_historical_overrun_rate"
    ]
    .last()
)


global_fallback_rate = (
    float(train_table["overrun_flag"].mean())
    if not train_table.empty
    else 0.0
)


avail_with_type = avail.merge(
    assets[["asset_id", "asset_type"]],
    on="asset_id",
    how="left",
)


overall_type_avail = (
    avail_with_type
    .groupby("asset_type")["available"]
    .apply(lambda s: (s == "YES").mean())
)


# Features that require one-hot encoding.
CATEGORICAL = [
    "day_of_week",
    "maintenance_type",
    "required_asset_type",
    "priority",
    "weather",
    "traffic_level",
]


# ============================================================
# REQUEST MODEL
# ============================================================

class BlockRequest(BaseModel):
    section_id: str
    maintenance_type: str
    required_asset_type: str
    priority: str
    weather: str
    planned_duration_min: float
    date: str  # YYYY-MM-DD


# ============================================================
# HOURLY SCORING
# ============================================================

def score_hour(
    section_id: str,
    hour: int,
    maintenance_type: str,
    required_asset_type: str,
    priority: str,
    weather: str,
    planned_duration_min: float,
    date: str,
):
    """
    Calculate the expected operational impact of a maintenance
    block starting at a particular hour.
    """

    # --------------------------------------------------------
    # 1. Traffic
    # --------------------------------------------------------

    try:
        trains_count, traffic_level = traffic_idx.loc[
            (section_id, hour)
        ]

    except KeyError:
        trains_count = 0.0
        traffic_level = "LOW"


    # --------------------------------------------------------
    # 2. Assets available in the requested section
    # --------------------------------------------------------

    assets_here = assets_count_idx.get(
        (section_id, required_asset_type),
        0,
    )


    # --------------------------------------------------------
    # 3. Daily asset availability
    # --------------------------------------------------------

    target_date = pd.Timestamp(date)

    day_records = avail_with_type[
        (avail_with_type["date"] == target_date)
        &
        (
            avail_with_type["asset_type"]
            == required_asset_type
        )
    ]


    if len(day_records) > 0:

        avail_pct = (
            day_records["available"] == "YES"
        ).mean()

        had_record = 1

    else:

        avail_pct = overall_type_avail.get(
            required_asset_type,
            0.7,
        )

        had_record = 0


    # --------------------------------------------------------
    # 4. Historical section overrun rate
    # --------------------------------------------------------

    section_rate = latest_section_rate.get(
        section_id,
        global_fallback_rate,
    )


    # --------------------------------------------------------
    # 5. Date features
    # --------------------------------------------------------

    d = target_date

    day_name = d.day_name()

    is_weekend = int(
        day_name in ["Saturday", "Sunday"]
    )


    # --------------------------------------------------------
    # 6. Create model input
    # --------------------------------------------------------

    raw = pd.DataFrame(
        [
            {
                "day_of_week": day_name,
                "maintenance_type": maintenance_type,
                "required_asset_type": required_asset_type,
                "priority": priority,
                "weather": weather,
                "traffic_level": traffic_level,
                "month": d.month,
                "is_weekend": is_weekend,
                "start_hour": hour,
                "trains_count": trains_count,
                "assets_of_type_in_section": assets_here,
                "asset_type_availability_pct": avail_pct,
                "had_availability_record": had_record,
                "section_historical_overrun_rate": section_rate,
                "planned_duration_min": planned_duration_min,
            }
        ]
    )


    # --------------------------------------------------------
    # 7. One-hot encode categorical variables
    # --------------------------------------------------------

    X_row = (
        pd.get_dummies(
            raw,
            columns=CATEGORICAL,
        )
        .reindex(
            columns=feature_columns,
            fill_value=0,
        )
    )


    # --------------------------------------------------------
    # 8. ML prediction
    # --------------------------------------------------------

    predicted_overrun = float(
        model.predict(X_row)[0]
    )


    # Negative overrun is not operationally useful.
    predicted_overrun = max(
        predicted_overrun,
        0.0,
    )


    # --------------------------------------------------------
    # 9. Expected duration
    # --------------------------------------------------------

    expected_total_duration = (
        planned_duration_min
        + predicted_overrun
    )


    # --------------------------------------------------------
    # 10. Disruption score
    # --------------------------------------------------------

    trains_count = float(trains_count)

    disruption_score = (
        trains_count
        * expected_total_duration
    )


    return {
        "trains_count": trains_count,

        "traffic_level": str(
            traffic_level
        ),

        "predicted_overrun_min": round(
            predicted_overrun,
            1,
        ),

        "expected_total_duration_min": round(
            expected_total_duration,
            1,
        ),

        "asset_type_availability_pct": round(
            float(avail_pct),
            2,
        ),

        "disruption_score": round(
            float(disruption_score),
            1,
        ),
    }


# ============================================================
# HEALTH CHECK
# ============================================================

@app.get("/api/health")
def health():
    """
    Backend health check.

    Example:
        GET /api/health
    """

    return {
        "status": "RailVinyas API is running"
    }


# ============================================================
# SECTION API
# ============================================================

@app.get("/api/sections")
def list_sections(
    user=Depends(get_current_user)
):
    """
    Return available railway section IDs.

    Requires authentication.
    """

    return sorted(
        traffic["section_id"]
        .dropna()
        .unique()
        .tolist()
    )[:1000]


# ============================================================
# RECOMMENDATION API
# ============================================================

@app.post("/api/recommend")
def recommend(
    req: BlockRequest,
    user=Depends(get_current_user),
):
    """
    Generate an AI-assisted maintenance block recommendation.

    The system:

    1. Validates the railway section.
    2. Evaluates all 24 hours.
    3. Predicts maintenance overrun.
    4. Calculates expected duration.
    5. Calculates disruption score.
    6. Ranks candidate hours.
    7. Selects the best maintenance asset.
    """

    # --------------------------------------------------------
    # Validate section
    # --------------------------------------------------------

    if req.section_id not in traffic["section_id"].values:

        raise HTTPException(
            status_code=404,
            detail=(
                f"Unknown section_id "
                f"'{req.section_id}'"
            ),
        )


    # --------------------------------------------------------
    # Evaluate all 24 candidate hours
    # --------------------------------------------------------

    candidates = []

    for hour in range(24):

        result = score_hour(
            section_id=req.section_id,
            hour=hour,
            maintenance_type=req.maintenance_type,
            required_asset_type=req.required_asset_type,
            priority=req.priority,
            weather=req.weather,
            planned_duration_min=req.planned_duration_min,
            date=req.date,
        )

        result["start_hour"] = hour

        candidates.append(result)


    # --------------------------------------------------------
    # Rank candidates
    # --------------------------------------------------------

    ranked = sorted(
        candidates,
        key=lambda x: x["disruption_score"],
    )


    best = ranked[0]


    # --------------------------------------------------------
    # Select maintenance asset
    # --------------------------------------------------------

    asset_candidates = assets[
        assets["asset_type"]
        == req.required_asset_type
    ].copy()


    if len(asset_candidates) > 0:

        # Prefer assets whose home section matches
        # the requested railway section.
        asset_candidates["home_match"] = (
            asset_candidates["home_section_id"]
            == req.section_id
        ).astype(int)


        asset_candidates = (
            asset_candidates
            .sort_values(
                ["home_match", "status"],
                ascending=[False, True],
            )
        )


        raw_selected = (
            asset_candidates.iloc[0]
            .to_dict()
        )


        selected = {
            key: (
                value.item()
                if hasattr(value, "item")
                else value
            )

            for key, value
            in raw_selected.items()
        }

    else:

        selected = None


    # --------------------------------------------------------
    # Persist this request to the live log (see /api/blocks/log)
    # --------------------------------------------------------

    log_id = log_recommendation(req, best, selected, user)


    # --------------------------------------------------------
    # Final response
    # --------------------------------------------------------

    return {
        "section_id": req.section_id,

        "maintenance_type":
            req.maintenance_type,

        "date":
            req.date,

        "recommended_start_hour":
            best["start_hour"],

        "expected_total_duration_min":
            best["expected_total_duration_min"],

        "predicted_overrun_min":
            best["predicted_overrun_min"],

        "traffic_level":
            best["traffic_level"],

        "trains_count":
            best["trains_count"],

        "disruption_score":
            best["disruption_score"],

        "selected_asset":
            selected,

        "top_5_candidates":
            ranked[:5],

        "log_id": log_id,
    }


# ============================================================
# DASHBOARD API
# ============================================================

@app.get("/api/dashboard/summary")
def dashboard_summary(user=Depends(get_current_user)):
    """Real counts from the actual loaded data -- no invented numbers.
    Falls back to the most recent month PRESENT IN THE DATA if the
    real current month has no records (the synthetic dataset only
    goes up to a fixed date range)."""
    now = pd.Timestamp.now()
    this_month_mask = (blocks_full["date"].dt.year == now.year) & (blocks_full["date"].dt.month == now.month)
    count = int(this_month_mask.sum())
    reference_month = now.strftime("%B %Y")

    if count == 0:
        latest = blocks_full["date"].max()
        fallback_mask = (blocks_full["date"].dt.year == latest.year) & (blocks_full["date"].dt.month == latest.month)
        count = int(fallback_mask.sum())
        reference_month = latest.strftime("%B %Y") + " (most recent month in dataset)"

    return {
        "total_sections_monitored": int(traffic["section_id"].nunique()),
        "total_assets": int(len(assets)),
        "blocks_scheduled_this_month": count,
        "blocks_scheduled_reference_month": reference_month,
        "avg_disruption_reduction_pct": AVG_DISRUPTION_REDUCTION,  # null if Step 4 evaluation wasn't run
    }


@app.get("/api/dashboard/recent")
def dashboard_recent(limit: int = 20, user=Depends(get_current_user)):
    """Most recent maintenance blocks from the synthetic dataset, formatted
    for the dashboard table. For genuinely live requests made through this
    app, see /api/blocks/log instead."""
    recent = blocks_full.sort_values("date", ascending=False).head(limit).copy()
    now = pd.Timestamp.now()
    rows = []
    for _, r in recent.iterrows():
        a, b, a_name, b_name = section_to_stations(r["section_id"])
        rows.append({
            "section_id": r["section_id"],
            "from_station": a_name, "to_station": b_name,
            "date": r["date"].strftime("%Y-%m-%d"),
            "maintenance_type": r["maintenance_type"],
            "recommended_time": r["planned_start"],
            "traffic_level": "LOW" if r["overrun_flag"] == 0 else "MEDIUM",
            "asset_type": r["required_asset_type"],
            "status": "Completed" if r["date"] < now else "Pending",
            "priority": r["priority"],
        })
    return rows


# ============================================================
# STATION / SECTION LOOKUP API
# ============================================================

@app.get("/api/sections/resolve")
def resolve_section(from_station: str, to_station: str, user=Depends(get_current_user)):
    """Turn two station codes into the section_id /api/recommend expects.
    Station-pair direction doesn't matter -- sections are undirected."""
    pair = sorted([from_station.upper(), to_station.upper()])
    section_id = "-".join(pair)
    match = traffic[traffic["section_id"] == section_id]
    if len(match) == 0:
        raise HTTPException(status_code=404,
                             detail=f"No direct section found between {from_station} and {to_station}")
    return {"section_id": section_id,
            "from_station": pair[0], "to_station": pair[1],
            "from_station_name": station_name_lookup.get(pair[0], pair[0]),
            "to_station_name": station_name_lookup.get(pair[1], pair[1])}


@app.get("/api/stations")
def list_stations(q: str = "", limit: int = 30, user=Depends(get_current_user)):
    """Searchable station list for the From/To dropdowns on New Block Request."""
    if q:
        matches = stations_master[
            stations_master["station_name"].str.contains(q, case=False, na=False) |
            stations_master["station_code"].str.contains(q, case=False, na=False)
        ]
    else:
        matches = stations_master
    return matches.head(limit).to_dict(orient="records")


# ============================================================
# SECTION TRAFFIC API
# ============================================================

@app.get("/api/section-traffic/heatmap")
def section_traffic_heatmap(limit: int = 40, user=Depends(get_current_user)):
    """Top N busiest sections x 24 hours, for the heatmap page."""
    totals = traffic.groupby("section_id")["trains_count"].sum().sort_values(ascending=False)
    top_sections = totals.head(limit).index.tolist()
    subset = traffic[traffic["section_id"].isin(top_sections)]

    result = []
    for sec in top_sections:
        sec_rows = subset[subset["section_id"] == sec].set_index("hour_of_day")
        a, b, a_name, b_name = section_to_stations(sec)
        hours = []
        for h in range(24):
            if h in sec_rows.index:
                hours.append({"hour": h, "trains_count": int(sec_rows.loc[h, "trains_count"]),
                              "traffic_level": sec_rows.loc[h, "traffic_level"]})
            else:
                hours.append({"hour": h, "trains_count": 0, "traffic_level": "LOW"})
        result.append({"section_id": sec, "from_station": a_name, "to_station": b_name, "hours": hours})
    return result


# ============================================================
# REPORTS API
# ============================================================

@app.get("/api/reports")
def reports(user=Depends(get_current_user)):
    """Optimizer-vs-baseline evaluation results, for the Reports page."""
    if eval_results is None:
        raise HTTPException(status_code=404,
                             detail="No evaluation results found. Run the Step 4 evaluation notebook first "
                                    "to generate 08_evaluation_results.csv.")
    return eval_results.to_dict(orient="records")


# ============================================================
# ASSET MANAGEMENT API
# ============================================================

@app.get("/api/assets")
def list_assets(user=Depends(get_current_user)):
    """Full asset register, for the Admin Panel's Asset Management tab.
    Status shown here merges the original CSV with any admin edits made
    via PATCH /api/assets/{asset_id} below (stored in railvinyas.db so
    edits persist across restarts without touching the source CSV)."""
    conn = get_db()
    overrides = {row["asset_id"]: row["status"] for row in
                 conn.execute("SELECT asset_id, status FROM asset_status_overrides").fetchall()}
    conn.close()

    result = assets.fillna("N/A").to_dict(orient="records")
    for r in result:
        if r["asset_id"] in overrides:
            r["status"] = overrides[r["asset_id"]]
    return result


class AssetStatusUpdate(BaseModel):
    status: str  # "Available" | "In Use" | "Under Repair"


@app.patch("/api/assets/{asset_id}")
def update_asset_status(asset_id: str, req: AssetStatusUpdate,
                         user=Depends(require_role("Admin"))):
    """Admin-only. Persists a status override in railvinyas.db."""
    if asset_id not in assets["asset_id"].values:
        raise HTTPException(status_code=404, detail=f"Unknown asset_id '{asset_id}'")
    if req.status not in ["Available", "In Use", "Under Repair"]:
        raise HTTPException(status_code=400, detail="status must be Available, In Use, or Under Repair")

    conn = get_db()
    conn.execute("""
        INSERT INTO asset_status_overrides (asset_id, status, updated_by, updated_at)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(asset_id) DO UPDATE SET status=excluded.status,
            updated_by=excluded.updated_by, updated_at=excluded.updated_at
    """, (asset_id, req.status, user["email"], pd.Timestamp.now().isoformat()))
    conn.commit()
    conn.close()
    return {"asset_id": asset_id, "status": req.status, "updated_by": user["email"]}


# ============================================================
# ADMIN / USER MANAGEMENT API
# ============================================================

@app.get("/api/admin/users")
def list_users(user=Depends(require_role("Admin"))):
    """Admin-only. Real user list from the auth database."""
    conn = get_db()
    rows = conn.execute("SELECT id, email, name, role, created_at FROM users ORDER BY id").fetchall()
    conn.close()
    return [dict(r) for r in rows]


class RoleUpdate(BaseModel):
    role: str  # "Admin" | "Section Controller" | "Viewer"


@app.patch("/api/admin/users/{user_id}")
def update_user_role(user_id: int, req: RoleUpdate, user=Depends(require_role("Admin"))):
    """Admin-only. Change another user's role."""
    if req.role not in ["Admin", "Section Controller", "Viewer"]:
        raise HTTPException(status_code=400, detail="role must be Admin, Section Controller, or Viewer")
    conn = get_db()
    result = conn.execute("UPDATE users SET role = ? WHERE id = ?", (req.role, user_id))
    conn.commit()
    if result.rowcount == 0:
        conn.close()
        raise HTTPException(status_code=404, detail="User not found")
    conn.close()
    return {"user_id": user_id, "role": req.role}


# ============================================================
# LIVE BLOCK REQUEST LOG API
# ============================================================

def init_extra_tables():
    """Tables for admin asset overrides and the live block-request log.
    Called once at startup, alongside auth.init_db()."""
    conn = get_db()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS asset_status_overrides (
            asset_id TEXT PRIMARY KEY,
            status TEXT NOT NULL,
            updated_by TEXT,
            updated_at TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS block_requests_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            section_id TEXT NOT NULL,
            date TEXT NOT NULL,
            maintenance_type TEXT NOT NULL,
            recommended_start_hour INTEGER,
            traffic_level TEXT,
            asset_id TEXT,
            disruption_score REAL,
            status TEXT NOT NULL DEFAULT 'Pending',
            requested_by TEXT,
            requested_at TEXT NOT NULL
        )
    """)
    conn.commit()
    conn.close()


init_extra_tables()


def log_recommendation(req, best, selected, user):
    """Persist every real /api/recommend call so Dashboard/Reports can show
    genuine request history instead of only the synthetic demo blocks."""
    conn = get_db()
    cur = conn.execute("""
        INSERT INTO block_requests_log
        (section_id, date, maintenance_type, recommended_start_hour, traffic_level,
         asset_id, disruption_score, status, requested_by, requested_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, 'Pending', ?, ?)
    """, (req.section_id, req.date, req.maintenance_type, best["start_hour"], best["traffic_level"],
          selected["asset_id"] if selected else None, best["disruption_score"],
          user["email"], pd.Timestamp.now().isoformat()))
    conn.commit()
    log_id = cur.lastrowid
    conn.close()
    return log_id


class ApproveRequest(BaseModel):
    log_id: int


@app.post("/api/blocks/approve")
def approve_block(req: ApproveRequest, user=Depends(require_role("Admin", "Section Controller"))):
    conn = get_db()
    result = conn.execute("UPDATE block_requests_log SET status = 'Approved' WHERE id = ?", (req.log_id,))
    conn.commit()
    if result.rowcount == 0:
        conn.close()
        raise HTTPException(status_code=404, detail="Request not found")
    conn.close()
    return {"log_id": req.log_id, "status": "Approved"}


@app.get("/api/blocks/log")
def blocks_log(limit: int = 20, user=Depends(get_current_user)):
    """Real, live log of actual /api/recommend calls made through this app --
    distinct from /api/dashboard/recent, which shows the synthetic demo
    dataset. This one starts EMPTY until someone submits a real request."""
    conn = get_db()
    rows = conn.execute(
        "SELECT * FROM block_requests_log ORDER BY id DESC LIMIT ?", (limit,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ============================================================
# REACT FRONTEND
# ============================================================
# IMPORTANT: everything above this section is an /api/... route. Nothing
# new should be added BELOW this point, because the catch-all route at
# the bottom will shadow any route defined after it.

if FRONTEND_DIST.exists():

    # Serve Vite-generated static assets:
    #
    # /assets/index-xxxx.js
    # /assets/index-xxxx.css
    #
    if (FRONTEND_DIST / "assets").exists():

        app.mount(
            "/assets",
            StaticFiles(
                directory=FRONTEND_DIST / "assets"
            ),
            name="assets",
        )


    @app.get(
        "/",
        include_in_schema=False,
    )
    async def serve_home():

        index_file = (
            FRONTEND_DIST
            / "index.html"
        )

        if index_file.exists():

            return FileResponse(
                index_file
            )

        return JSONResponse(
            {
                "status":
                    "RailVinyas API is running",
                "message":
                    "Frontend build not found.",
            }
        )


    @app.get(
        "/{full_path:path}",
        include_in_schema=False,
    )
    async def serve_frontend(
        full_path: str
    ):

        # Prevent path traversal.
        requested_file = (
            FRONTEND_DIST
            / full_path
        ).resolve()

        frontend_root = (
            FRONTEND_DIST.resolve()
        )

        try:

            requested_file.relative_to(
                frontend_root
            )

        except ValueError:

            return FileResponse(
                FRONTEND_DIST / "index.html"
            )


        # Serve an existing file.
        if requested_file.is_file():

            return FileResponse(
                requested_file
            )


        # React Router fallback.
        return FileResponse(
            FRONTEND_DIST / "index.html"
        )


# ============================================================
# LOCAL DEVELOPMENT
# ============================================================

if __name__ == "__main__":

    import uvicorn

    uvicorn.run(
        "backend.app:app",
        host="127.0.0.1",
        port=8000,
        reload=True,
    )